apiVersion: v1
kind: Service
metadata:
  name: storage-server-service
spec:
  selector:
    app: file-storage
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30009
      name: socket-port
  type: NodePort
